jobs:
  - url: https://raw.githubusercontent.com/adhocteam/jenkins/master/jobs/disable_telemetry.groovy
  - url: https://raw.githubusercontent.com/adhocteam/jenkins/ce20ebe5555cd2b6c1978a88980d4fa4f9e2c370/jobs/setup_gh_org_folder.groovy
  - url: https://raw.githubusercontent.com/adhocteam/jenkins/master/jobs/docker_cleanup.groovy
