jobs:
  - url: https://raw.githubusercontent.com/adhocteam/jenkins/master/jobs/disable_telemetry.groovy
  - url: https://raw.githubusercontent.com/adhocteam/jenkins/mpsm/jobs/setup_repo.groovy
  - url: https://raw.githubusercontent.com/adhocteam/jenkins/master/jobs/docker_cleanup.groovy

